# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(901, 577)
        MainWindow.setStyleSheet(_fromUtf8("QFrame{\n"
        "background-color:rgb(255, 255, 255);\n"
        "border: 1px solid rgb(147, 147, 147)\n"
        "}\n"
        "\n"
        "QLabel{\n"
        "border:none;\n"
        "background-color:transparent;\n"
        "}\n"
        "\n"
        "QToolButton{\n"
        "background-color:transparent;\n"
        "border:none;\n"
        "}\n"
        "\n"
        "QToolButton:pressed{\n"
        "background-color:rgb(231, 226, 221);\n"
        "border: 1px solid rgb(147, 147, 147);\n"
        "}\n"
        "\n"
        "QToolButton:checked{\n"
        "background-color:rgb(231, 226, 221);\n"
        "border: 1px solid rgb(147, 147, 147);\n"
        "}\n"
        "\n"
        "QToolButton:hover {\n"
        "background-color:rgb(188, 188, 188);\n"
        "}\n"
        "\n"
        "QStackedWidget {\n"
        "background-color:rgb(220, 228, 244);\n"
        "border: 1px solid rgb(147, 147, 147)\n"
        "}"))

        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.buttons_frame = QtGui.QFrame(self.centralwidget)
        self.buttons_frame.setGeometry(QtCore.QRect(180, 10, 711, 71))
        self.buttons_frame.setStyleSheet(_fromUtf8(""))
        self.buttons_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttons_frame.setObjectName(_fromUtf8("buttons_frame"))

        self.main_but = QtGui.QToolButton(self.buttons_frame)
        self.main_but.setGeometry(QtCore.QRect(10, 10, 131, 51))
        self.main_but.setCheckable(True)
        self.main_but.setAutoExclusive(True)
        self.main_but.setObjectName(_fromUtf8("main_but"))
        self.main_but.clicked.connect(self.page1)

        self.config_but = QtGui.QToolButton(self.buttons_frame)
        self.config_but.setGeometry(QtCore.QRect(150, 10, 131, 51))
        self.config_but.setCheckable(True)
        self.config_but.setAutoExclusive(True)
        self.config_but.setObjectName(_fromUtf8("config_but"))
        self.config_but.clicked.connect(self.page2)

        self.pin_but = QtGui.QToolButton(self.buttons_frame)
        self.pin_but.setGeometry(QtCore.QRect(290, 10, 131, 51))
        self.pin_but.setCheckable(True)
        self.pin_but.setAutoExclusive(True)
        self.pin_but.setObjectName(_fromUtf8("pin_but"))
        self.pin_but.clicked.connect(self.page3)

        self.protec_but = QtGui.QToolButton(self.buttons_frame)
        self.protec_but.setGeometry(QtCore.QRect(430, 10, 131, 51))
        self.protec_but.setCheckable(True)
        self.protec_but.setAutoExclusive(True)
        self.protec_but.setObjectName(_fromUtf8("protec_but"))
        self.protec_but.clicked.connect(self.page4)

        self.monitor_but = QtGui.QToolButton(self.buttons_frame)
        self.monitor_but.setGeometry(QtCore.QRect(570, 10, 131, 51))
        self.monitor_but.setCheckable(True)
        self.monitor_but.setAutoExclusive(True)
        self.monitor_but.setObjectName(_fromUtf8("monitor_but"))
        self.monitor_but.clicked.connect(self.page5)

        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 90, 711, 431))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet(_fromUtf8(""))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.voltage_box = QtGui.QGroupBox(self.page)
        self.voltage_box.setGeometry(QtCore.QRect(260, 190, 371, 131))
        self.voltage_box.setObjectName(_fromUtf8("voltage_box"))
        self.vin_value_main = QtGui.QLineEdit(self.voltage_box)
        self.vin_value_main.setGeometry(QtCore.QRect(60, 50, 81, 21))
        self.vin_value_main.setObjectName(_fromUtf8("vin_value_main"))
        self.vout_value_main = QtGui.QLineEdit(self.voltage_box)
        self.vout_value_main.setGeometry(QtCore.QRect(60, 100, 81, 21))
        self.vout_value_main.setObjectName(_fromUtf8("vout_value_main"))
        self.margin_high = QtGui.QLineEdit(self.voltage_box)
        self.margin_high.setGeometry(QtCore.QRect(190, 80, 51, 21))
        self.margin_high.setObjectName(_fromUtf8("margin_high"))
        self.margin_low = QtGui.QLineEdit(self.voltage_box)
        self.margin_low.setGeometry(QtCore.QRect(270, 80, 51, 21))
        self.margin_low.setObjectName(_fromUtf8("margin_low"))
        self.vin_label_main = QtGui.QLabel(self.voltage_box)
        self.vin_label_main.setGeometry(QtCore.QRect(20, 50, 21, 20))
        self.vin_label_main.setObjectName(_fromUtf8("vin_label_main"))
        self.vout_label_main = QtGui.QLabel(self.voltage_box)
        self.vout_label_main.setGeometry(QtCore.QRect(20, 100, 31, 20))
        self.vout_label_main.setObjectName(_fromUtf8("vout_label_main"))
        self.label_3 = QtGui.QLabel(self.voltage_box)
        self.label_3.setGeometry(QtCore.QRect(150, 50, 21, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.voltage_box)
        self.label_4.setGeometry(QtCore.QRect(150, 100, 21, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.procent_label1 = QtGui.QLabel(self.voltage_box)
        self.procent_label1.setGeometry(QtCore.QRect(250, 80, 21, 20))
        self.procent_label1.setObjectName(_fromUtf8("procent_label1"))
        self.procent_label2 = QtGui.QLabel(self.voltage_box)
        self.procent_label2.setGeometry(QtCore.QRect(330, 80, 21, 20))
        self.procent_label2.setObjectName(_fromUtf8("procent_label2"))
        self.nominal_label = QtGui.QLabel(self.voltage_box)
        self.nominal_label.setGeometry(QtCore.QRect(60, 20, 61, 20))
        self.nominal_label.setObjectName(_fromUtf8("nominal_label"))
        self.margin_high_label = QtGui.QLabel(self.voltage_box)
        self.margin_high_label.setGeometry(QtCore.QRect(190, 50, 61, 20))
        self.margin_high_label.setObjectName(_fromUtf8("margin_high_label"))
        self.margin_low_label = QtGui.QLabel(self.voltage_box)
        self.margin_low_label.setGeometry(QtCore.QRect(270, 50, 61, 20))
        self.margin_low_label.setObjectName(_fromUtf8("margin_low_label"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.configuration_box = QtGui.QGroupBox(self.page_2)
        self.configuration_box.setGeometry(QtCore.QRect(20, 10, 671, 401))
        self.configuration_box.setObjectName(_fromUtf8("configuration_box"))
        self.dev_rise = QtGui.QLabel(self.configuration_box)
        self.dev_rise.setGeometry(QtCore.QRect(10, 330, 61, 20))
        self.dev_rise.setObjectName(_fromUtf8("dev_rise"))
        self.dev_fall = QtGui.QLabel(self.configuration_box)
        self.dev_fall.setGeometry(QtCore.QRect(10, 360, 61, 20))
        self.dev_fall.setObjectName(_fromUtf8("dev_fall"))
        self.delay = QtGui.QLabel(self.configuration_box)
        self.delay.setGeometry(QtCore.QRect(90, 290, 31, 20))
        self.delay.setObjectName(_fromUtf8("delay"))
        self.ton_delay_label = QtGui.QLabel(self.configuration_box)
        self.ton_delay_label.setGeometry(QtCore.QRect(90, 330, 61, 20))
        self.ton_delay_label.setObjectName(_fromUtf8("ton_delay_label"))
        self.toff_delay_label = QtGui.QLabel(self.configuration_box)
        self.toff_delay_label.setGeometry(QtCore.QRect(90, 360, 61, 20))
        self.toff_delay_label.setObjectName(_fromUtf8("toff_delay_label"))
        self.ton_rise_label = QtGui.QLabel(self.configuration_box)
        self.ton_rise_label.setGeometry(QtCore.QRect(250, 330, 61, 20))
        self.ton_rise_label.setObjectName(_fromUtf8("ton_rise_label"))
        self.toff_fall_label = QtGui.QLabel(self.configuration_box)
        self.toff_fall_label.setGeometry(QtCore.QRect(250, 360, 61, 20))
        self.toff_fall_label.setObjectName(_fromUtf8("toff_fall_label"))
        self.ton_max_label = QtGui.QLabel(self.configuration_box)
        self.ton_max_label.setGeometry(QtCore.QRect(410, 330, 51, 20))
        self.ton_max_label.setObjectName(_fromUtf8("ton_max_label"))
        self.toff_max_label = QtGui.QLabel(self.configuration_box)
        self.toff_max_label.setGeometry(QtCore.QRect(410, 360, 61, 20))
        self.toff_max_label.setObjectName(_fromUtf8("toff_max_label"))
        self.label_39 = QtGui.QLabel(self.configuration_box)
        self.label_39.setGeometry(QtCore.QRect(210, 330, 21, 20))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.configuration_box)
        self.label_40.setGeometry(QtCore.QRect(210, 360, 21, 20))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.configuration_box)
        self.label_41.setGeometry(QtCore.QRect(370, 330, 21, 20))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.configuration_box)
        self.label_42.setGeometry(QtCore.QRect(370, 360, 21, 20))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.ton_delay = QtGui.QLineEdit(self.configuration_box)
        self.ton_delay.setGeometry(QtCore.QRect(160, 330, 41, 21))
        self.ton_delay.setObjectName(_fromUtf8("ton_delay"))
        self.toff_delay = QtGui.QLineEdit(self.configuration_box)
        self.toff_delay.setGeometry(QtCore.QRect(160, 360, 41, 21))
        self.toff_delay.setObjectName(_fromUtf8("toff_delay"))
        self.lineEdit_19 = QtGui.QLineEdit(self.configuration_box)
        self.lineEdit_19.setGeometry(QtCore.QRect(320, 330, 41, 21))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.toff_fall = QtGui.QLineEdit(self.configuration_box)
        self.toff_fall.setGeometry(QtCore.QRect(320, 360, 41, 21))
        self.toff_fall.setObjectName(_fromUtf8("toff_fall"))
        self.ton_max = QtGui.QLineEdit(self.configuration_box)
        self.ton_max.setGeometry(QtCore.QRect(480, 330, 41, 21))
        self.ton_max.setObjectName(_fromUtf8("ton_max"))
        self.toff_max = QtGui.QLineEdit(self.configuration_box)
        self.toff_max.setGeometry(QtCore.QRect(480, 360, 41, 21))
        self.toff_max.setObjectName(_fromUtf8("toff_max"))
        self.label_43 = QtGui.QLabel(self.configuration_box)
        self.label_43.setGeometry(QtCore.QRect(530, 330, 21, 20))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.configuration_box)
        self.label_44.setGeometry(QtCore.QRect(530, 360, 21, 20))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.vout_on_label = QtGui.QLabel(self.configuration_box)
        self.vout_on_label.setGeometry(QtCore.QRect(570, 330, 21, 20))
        self.vout_on_label.setObjectName(_fromUtf8("vout_on_label"))
        self.vout_ff_label = QtGui.QLabel(self.configuration_box)
        self.vout_ff_label.setGeometry(QtCore.QRect(570, 360, 31, 20))
        self.vout_ff_label.setObjectName(_fromUtf8("vout_ff_label"))
        self.vout_on = QtGui.QLineEdit(self.configuration_box)
        self.vout_on.setGeometry(QtCore.QRect(600, 330, 41, 21))
        self.vout_on.setObjectName(_fromUtf8("vout_on"))
        self.out_off = QtGui.QLineEdit(self.configuration_box)
        self.out_off.setGeometry(QtCore.QRect(600, 360, 41, 21))
        self.out_off.setObjectName(_fromUtf8("out_off"))
        self.label_47 = QtGui.QLabel(self.configuration_box)
        self.label_47.setGeometry(QtCore.QRect(650, 330, 21, 20))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.configuration_box)
        self.label_48.setGeometry(QtCore.QRect(650, 360, 21, 20))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.ramping = QtGui.QLabel(self.configuration_box)
        self.ramping.setGeometry(QtCore.QRect(250, 290, 51, 20))
        self.ramping.setObjectName(_fromUtf8("ramping"))
        self.max_timing = QtGui.QLabel(self.configuration_box)
        self.max_timing.setGeometry(QtCore.QRect(410, 290, 61, 20))
        self.max_timing.setObjectName(_fromUtf8("max_timing"))
        self.vout = QtGui.QLabel(self.configuration_box)
        self.vout.setGeometry(QtCore.QRect(570, 290, 31, 20))
        self.vout.setObjectName(_fromUtf8("vout"))
        self.graph_frame = QtGui.QFrame(self.configuration_box)
        self.graph_frame.setGeometry(QtCore.QRect(20, 20, 631, 251))
        self.graph_frame.setStyleSheet(_fromUtf8(""))
        self.graph_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graph_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.graph_frame.setObjectName(_fromUtf8("graph_frame"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.protection_box = QtGui.QGroupBox(self.page_4)
        self.protection_box.setGeometry(QtCore.QRect(20, 10, 671, 411))
        self.protection_box.setObjectName(_fromUtf8("protection_box"))
        self.vout_ov_enable = QtGui.QCheckBox(self.protection_box)
        self.vout_ov_enable.setGeometry(QtCore.QRect(90, 90, 16, 17))
        self.vout_ov_enable.setText(_fromUtf8(""))
        self.vout_ov_enable.setObjectName(_fromUtf8("vout_ov_enable"))
        self.vout_uv_enable = QtGui.QCheckBox(self.protection_box)
        self.vout_uv_enable.setGeometry(QtCore.QRect(90, 140, 16, 17))
        self.vout_uv_enable.setText(_fromUtf8(""))
        self.vout_uv_enable.setObjectName(_fromUtf8("vout_uv_enable"))
        self.vin_ov_enable = QtGui.QCheckBox(self.protection_box)
        self.vin_ov_enable.setGeometry(QtCore.QRect(90, 190, 16, 17))
        self.vin_ov_enable.setText(_fromUtf8(""))
        self.vin_ov_enable.setObjectName(_fromUtf8("vin_ov_enable"))
        self.vin_uv_enable = QtGui.QCheckBox(self.protection_box)
        self.vin_uv_enable.setGeometry(QtCore.QRect(90, 240, 16, 17))
        self.vin_uv_enable.setText(_fromUtf8(""))
        self.vin_uv_enable.setObjectName(_fromUtf8("vin_uv_enable"))
        self.vout_ov_label = QtGui.QLabel(self.protection_box)
        self.vout_ov_label.setGeometry(QtCore.QRect(20, 90, 61, 20))
        self.vout_ov_label.setObjectName(_fromUtf8("vout_ov_label"))
        self.vin_ov_label = QtGui.QLabel(self.protection_box)
        self.vin_ov_label.setGeometry(QtCore.QRect(20, 190, 46, 13))
        self.vin_ov_label.setObjectName(_fromUtf8("vin_ov_label"))
        self.warning_label = QtGui.QLabel(self.protection_box)
        self.warning_label.setGeometry(QtCore.QRect(170, 30, 71, 16))
        self.warning_label.setObjectName(_fromUtf8("warning_label"))
        self.iout_oc_label = QtGui.QLabel(self.protection_box)
        self.iout_oc_label.setGeometry(QtCore.QRect(20, 290, 46, 13))
        self.iout_oc_label.setObjectName(_fromUtf8("iout_oc_label"))
        self.enable_label = QtGui.QLabel(self.protection_box)
        self.enable_label.setGeometry(QtCore.QRect(80, 30, 41, 16))
        self.enable_label.setObjectName(_fromUtf8("enable_label"))
        self.temp_ot_label = QtGui.QLabel(self.protection_box)
        self.temp_ot_label.setGeometry(QtCore.QRect(20, 340, 46, 13))
        self.temp_ot_label.setObjectName(_fromUtf8("temp_ot_label"))
        self.fault_label = QtGui.QLabel(self.protection_box)
        self.fault_label.setGeometry(QtCore.QRect(310, 30, 51, 16))
        self.fault_label.setObjectName(_fromUtf8("fault_label"))
        self.delay_label = QtGui.QLabel(self.protection_box)
        self.delay_label.setGeometry(QtCore.QRect(450, 30, 61, 16))
        self.delay_label.setObjectName(_fromUtf8("delay_label"))
        self.vout_ov_warning = QtGui.QLineEdit(self.protection_box)
        self.vout_ov_warning.setGeometry(QtCore.QRect(160, 90, 81, 21))
        self.vout_ov_warning.setObjectName(_fromUtf8("vout_ov_warning"))
        self.vout_uv_warning = QtGui.QLineEdit(self.protection_box)
        self.vout_uv_warning.setGeometry(QtCore.QRect(160, 140, 81, 21))
        self.vout_uv_warning.setObjectName(_fromUtf8("vout_uv_warning"))
        self.vin_ov_warning = QtGui.QLineEdit(self.protection_box)
        self.vin_ov_warning.setGeometry(QtCore.QRect(160, 190, 81, 21))
        self.vin_ov_warning.setObjectName(_fromUtf8("vin_ov_warning"))
        self.vin_uv_warning = QtGui.QLineEdit(self.protection_box)
        self.vin_uv_warning.setGeometry(QtCore.QRect(160, 240, 81, 21))
        self.vin_uv_warning.setObjectName(_fromUtf8("vin_uv_warning"))
        self.vout_ov_fault = QtGui.QLineEdit(self.protection_box)
        self.vout_ov_fault.setGeometry(QtCore.QRect(300, 90, 81, 21))
        self.vout_ov_fault.setObjectName(_fromUtf8("vout_ov_fault"))
        self.vout_uv_fault = QtGui.QLineEdit(self.protection_box)
        self.vout_uv_fault.setGeometry(QtCore.QRect(300, 140, 81, 21))
        self.vout_uv_fault.setObjectName(_fromUtf8("vout_uv_fault"))
        self.vin_ov_fault = QtGui.QLineEdit(self.protection_box)
        self.vin_ov_fault.setGeometry(QtCore.QRect(300, 190, 81, 21))
        self.vin_ov_fault.setObjectName(_fromUtf8("vin_ov_fault"))
        self.vin_uv_fault = QtGui.QLineEdit(self.protection_box)
        self.vin_uv_fault.setGeometry(QtCore.QRect(300, 240, 81, 21))
        self.vin_uv_fault.setObjectName(_fromUtf8("vin_uv_fault"))
        self.vout_ov_delay = QtGui.QLineEdit(self.protection_box)
        self.vout_ov_delay.setGeometry(QtCore.QRect(440, 90, 81, 21))
        self.vout_ov_delay.setObjectName(_fromUtf8("vout_ov_delay"))
        self.vout_uv_delay = QtGui.QLineEdit(self.protection_box)
        self.vout_uv_delay.setGeometry(QtCore.QRect(440, 140, 81, 21))
        self.vout_uv_delay.setObjectName(_fromUtf8("vout_uv_delay"))
        self.vin_ov_delay = QtGui.QLineEdit(self.protection_box)
        self.vin_ov_delay.setGeometry(QtCore.QRect(440, 190, 81, 21))
        self.vin_ov_delay.setObjectName(_fromUtf8("vin_ov_delay"))
        self.iout_oc_delay = QtGui.QLineEdit(self.protection_box)
        self.iout_oc_delay.setGeometry(QtCore.QRect(440, 290, 81, 21))
        self.iout_oc_delay.setObjectName(_fromUtf8("iout_oc_delay"))
        self.v_label1 = QtGui.QLabel(self.protection_box)
        self.v_label1.setGeometry(QtCore.QRect(250, 90, 21, 20))
        self.v_label1.setObjectName(_fromUtf8("v_label1"))
        self.v_label2 = QtGui.QLabel(self.protection_box)
        self.v_label2.setGeometry(QtCore.QRect(250, 140, 21, 20))
        self.v_label2.setObjectName(_fromUtf8("v_label2"))
        self.v_label3 = QtGui.QLabel(self.protection_box)
        self.v_label3.setGeometry(QtCore.QRect(250, 190, 21, 20))
        self.v_label3.setObjectName(_fromUtf8("v_label3"))
        self.v_label4 = QtGui.QLabel(self.protection_box)
        self.v_label4.setGeometry(QtCore.QRect(250, 240, 21, 20))
        self.v_label4.setObjectName(_fromUtf8("v_label4"))
        self.v_label5 = QtGui.QLabel(self.protection_box)
        self.v_label5.setGeometry(QtCore.QRect(390, 90, 21, 20))
        self.v_label5.setObjectName(_fromUtf8("v_label5"))
        self.v_label6 = QtGui.QLabel(self.protection_box)
        self.v_label6.setGeometry(QtCore.QRect(390, 140, 21, 20))
        self.v_label6.setObjectName(_fromUtf8("v_label6"))
        self.v_label7 = QtGui.QLabel(self.protection_box)
        self.v_label7.setGeometry(QtCore.QRect(390, 190, 21, 20))
        self.v_label7.setObjectName(_fromUtf8("v_label7"))
        self.v_label8 = QtGui.QLabel(self.protection_box)
        self.v_label8.setGeometry(QtCore.QRect(390, 240, 21, 20))
        self.v_label8.setObjectName(_fromUtf8("v_label8"))
        self.ms_label1 = QtGui.QLabel(self.protection_box)
        self.ms_label1.setGeometry(QtCore.QRect(530, 90, 21, 20))
        self.ms_label1.setObjectName(_fromUtf8("ms_label1"))
        self.ms_label2 = QtGui.QLabel(self.protection_box)
        self.ms_label2.setGeometry(QtCore.QRect(530, 140, 21, 20))
        self.ms_label2.setObjectName(_fromUtf8("ms_label2"))
        self.ms_label3 = QtGui.QLabel(self.protection_box)
        self.ms_label3.setGeometry(QtCore.QRect(530, 190, 21, 20))
        self.ms_label3.setObjectName(_fromUtf8("ms_label3"))
        self.ms_label4 = QtGui.QLabel(self.protection_box)
        self.ms_label4.setGeometry(QtCore.QRect(530, 240, 21, 20))
        self.ms_label4.setObjectName(_fromUtf8("ms_label4"))
        self.alert_label = QtGui.QLabel(self.protection_box)
        self.alert_label.setGeometry(QtCore.QRect(590, 30, 31, 16))
        self.alert_label.setObjectName(_fromUtf8("alert_label"))
        self.vout_uv_label = QtGui.QLabel(self.protection_box)
        self.vout_uv_label.setGeometry(QtCore.QRect(20, 140, 51, 16))
        self.vout_uv_label.setObjectName(_fromUtf8("vout_uv_label"))
        self.vin_uv_label = QtGui.QLabel(self.protection_box)
        self.vin_uv_label.setGeometry(QtCore.QRect(20, 240, 46, 13))
        self.vin_uv_label.setObjectName(_fromUtf8("vin_uv_label"))
        self.temp_ot_enable = QtGui.QCheckBox(self.protection_box)
        self.temp_ot_enable.setGeometry(QtCore.QRect(90, 340, 16, 17))
        self.temp_ot_enable.setText(_fromUtf8(""))
        self.temp_ot_enable.setObjectName(_fromUtf8("temp_ot_enable"))
        self.iout_oc_enable = QtGui.QCheckBox(self.protection_box)
        self.iout_oc_enable.setGeometry(QtCore.QRect(90, 290, 16, 17))
        self.iout_oc_enable.setText(_fromUtf8(""))
        self.iout_oc_enable.setObjectName(_fromUtf8("iout_oc_enable"))
        self.iout_oc_warning = QtGui.QLineEdit(self.protection_box)
        self.iout_oc_warning.setGeometry(QtCore.QRect(160, 290, 81, 21))
        self.iout_oc_warning.setObjectName(_fromUtf8("iout_oc_warning"))
        self.temp_ot_warning = QtGui.QLineEdit(self.protection_box)
        self.temp_ot_warning.setGeometry(QtCore.QRect(160, 340, 81, 21))
        self.temp_ot_warning.setObjectName(_fromUtf8("temp_ot_warning"))
        self.temp_ot_fault = QtGui.QLineEdit(self.protection_box)
        self.temp_ot_fault.setGeometry(QtCore.QRect(300, 340, 81, 21))
        self.temp_ot_fault.setObjectName(_fromUtf8("temp_ot_fault"))
        self.iout_oc_fault = QtGui.QLineEdit(self.protection_box)
        self.iout_oc_fault.setGeometry(QtCore.QRect(300, 290, 81, 21))
        self.iout_oc_fault.setObjectName(_fromUtf8("iout_oc_fault"))
        self.vin_uv_delay = QtGui.QLineEdit(self.protection_box)
        self.vin_uv_delay.setGeometry(QtCore.QRect(440, 240, 81, 21))
        self.vin_uv_delay.setObjectName(_fromUtf8("vin_uv_delay"))
        self.temp_ot_delay = QtGui.QLineEdit(self.protection_box)
        self.temp_ot_delay.setGeometry(QtCore.QRect(440, 340, 81, 21))
        self.temp_ot_delay.setObjectName(_fromUtf8("temp_ot_delay"))
        self.c_label1 = QtGui.QLabel(self.protection_box)
        self.c_label1.setGeometry(QtCore.QRect(250, 340, 21, 20))
        self.c_label1.setObjectName(_fromUtf8("c_label1"))
        self.a_label1 = QtGui.QLabel(self.protection_box)
        self.a_label1.setGeometry(QtCore.QRect(250, 290, 21, 20))
        self.a_label1.setObjectName(_fromUtf8("a_label1"))
        self.ms_label5 = QtGui.QLabel(self.protection_box)
        self.ms_label5.setGeometry(QtCore.QRect(530, 290, 21, 20))
        self.ms_label5.setObjectName(_fromUtf8("ms_label5"))
        self.ms_label6 = QtGui.QLabel(self.protection_box)
        self.ms_label6.setGeometry(QtCore.QRect(530, 340, 21, 20))
        self.ms_label6.setObjectName(_fromUtf8("ms_label6"))
        self.c_label2 = QtGui.QLabel(self.protection_box)
        self.c_label2.setGeometry(QtCore.QRect(390, 340, 21, 20))
        self.c_label2.setObjectName(_fromUtf8("c_label2"))
        self.a_label2 = QtGui.QLabel(self.protection_box)
        self.a_label2.setGeometry(QtCore.QRect(390, 290, 21, 20))
        self.a_label2.setObjectName(_fromUtf8("a_label2"))
        self.w_label = QtGui.QLabel(self.protection_box)
        self.w_label.setGeometry(QtCore.QRect(580, 60, 21, 20))
        self.w_label.setObjectName(_fromUtf8("w_label"))
        self.f_label = QtGui.QLabel(self.protection_box)
        self.f_label.setGeometry(QtCore.QRect(620, 60, 21, 20))
        self.f_label.setObjectName(_fromUtf8("f_label"))
        self.vout_ov_walert = QtGui.QCheckBox(self.protection_box)
        self.vout_ov_walert.setGeometry(QtCore.QRect(580, 90, 16, 17))
        self.vout_ov_walert.setText(_fromUtf8(""))
        self.vout_ov_walert.setObjectName(_fromUtf8("vout_ov_walert"))
        self.vout_uv_walert = QtGui.QCheckBox(self.protection_box)
        self.vout_uv_walert.setGeometry(QtCore.QRect(580, 140, 16, 17))
        self.vout_uv_walert.setText(_fromUtf8(""))
        self.vout_uv_walert.setObjectName(_fromUtf8("vout_uv_walert"))
        self.vin_ov_walert = QtGui.QCheckBox(self.protection_box)
        self.vin_ov_walert.setGeometry(QtCore.QRect(580, 190, 16, 17))
        self.vin_ov_walert.setText(_fromUtf8(""))
        self.vin_ov_walert.setObjectName(_fromUtf8("vin_ov_walert"))
        self.vin_uv_walert = QtGui.QCheckBox(self.protection_box)
        self.vin_uv_walert.setGeometry(QtCore.QRect(580, 240, 16, 17))
        self.vin_uv_walert.setText(_fromUtf8(""))
        self.vin_uv_walert.setObjectName(_fromUtf8("vin_uv_walert"))
        self.iout_oc_walert = QtGui.QCheckBox(self.protection_box)
        self.iout_oc_walert.setGeometry(QtCore.QRect(580, 290, 16, 17))
        self.iout_oc_walert.setText(_fromUtf8(""))
        self.iout_oc_walert.setObjectName(_fromUtf8("iout_oc_walert"))
        self.temp_ot_walert = QtGui.QCheckBox(self.protection_box)
        self.temp_ot_walert.setGeometry(QtCore.QRect(580, 340, 16, 17))
        self.temp_ot_walert.setText(_fromUtf8(""))
        self.temp_ot_walert.setObjectName(_fromUtf8("temp_ot_walert"))
        self.vout_ov_falert = QtGui.QCheckBox(self.protection_box)
        self.vout_ov_falert.setGeometry(QtCore.QRect(620, 90, 16, 17))
        self.vout_ov_falert.setText(_fromUtf8(""))
        self.vout_ov_falert.setObjectName(_fromUtf8("vout_ov_falert"))
        self.vout_uv_falert = QtGui.QCheckBox(self.protection_box)
        self.vout_uv_falert.setGeometry(QtCore.QRect(620, 140, 16, 17))
        self.vout_uv_falert.setText(_fromUtf8(""))
        self.vout_uv_falert.setObjectName(_fromUtf8("vout_uv_falert"))
        self.vin_ov_falert = QtGui.QCheckBox(self.protection_box)
        self.vin_ov_falert.setGeometry(QtCore.QRect(620, 190, 16, 17))
        self.vin_ov_falert.setText(_fromUtf8(""))
        self.vin_ov_falert.setObjectName(_fromUtf8("vin_ov_falert"))
        self.vin_uv_falert = QtGui.QCheckBox(self.protection_box)
        self.vin_uv_falert.setGeometry(QtCore.QRect(620, 240, 16, 17))
        self.vin_uv_falert.setText(_fromUtf8(""))
        self.vin_uv_falert.setObjectName(_fromUtf8("vin_uv_falert"))
        self.iout_oc_falert = QtGui.QCheckBox(self.protection_box)
        self.iout_oc_falert.setGeometry(QtCore.QRect(620, 290, 16, 17))
        self.iout_oc_falert.setText(_fromUtf8(""))
        self.iout_oc_falert.setObjectName(_fromUtf8("iout_oc_falert"))
        self.temp_oc_falert = QtGui.QCheckBox(self.protection_box)
        self.temp_oc_falert.setGeometry(QtCore.QRect(620, 340, 16, 17))
        self.temp_oc_falert.setText(_fromUtf8(""))
        self.temp_oc_falert.setObjectName(_fromUtf8("temp_oc_falert"))
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.monitoring_box = QtGui.QGroupBox(self.page_5)
        self.monitoring_box.setGeometry(QtCore.QRect(20, 10, 671, 401))
        self.monitoring_box.setObjectName(_fromUtf8("monitoring_box"))
        self.clear_faults_but = QtGui.QPushButton(self.monitoring_box)
        self.clear_faults_but.setGeometry(QtCore.QRect(20, 260, 75, 23))
        self.clear_faults_but.setObjectName(_fromUtf8("clear_faults_but"))
        self.vin_label = QtGui.QLabel(self.monitoring_box)
        self.vin_label.setGeometry(QtCore.QRect(30, 50, 31, 21))
        self.vin_label.setObjectName(_fromUtf8("vin_label"))
        self.vout_label = QtGui.QLabel(self.monitoring_box)
        self.vout_label.setGeometry(QtCore.QRect(30, 100, 41, 20))
        self.vout_label.setObjectName(_fromUtf8("vout_label"))
        self.iout_label = QtGui.QLabel(self.monitoring_box)
        self.iout_label.setGeometry(QtCore.QRect(30, 150, 31, 20))
        self.iout_label.setObjectName(_fromUtf8("iout_label"))
        self.temp_label = QtGui.QLabel(self.monitoring_box)
        self.temp_label.setGeometry(QtCore.QRect(30, 200, 41, 20))
        self.temp_label.setObjectName(_fromUtf8("temp_label"))
        self.vin_value = QtGui.QLabel(self.monitoring_box)
        self.vin_value.setGeometry(QtCore.QRect(90, 50, 46, 21))
        self.vin_value.setObjectName(_fromUtf8("vin_value"))
        self.vout_value = QtGui.QLabel(self.monitoring_box)
        self.vout_value.setGeometry(QtCore.QRect(90, 100, 46, 21))
        self.vout_value.setObjectName(_fromUtf8("vout_value"))
        self.iout_value = QtGui.QLabel(self.monitoring_box)
        self.iout_value.setGeometry(QtCore.QRect(90, 150, 46, 21))
        self.iout_value.setObjectName(_fromUtf8("iout_value"))
        self.temp_value = QtGui.QLabel(self.monitoring_box)
        self.temp_value.setGeometry(QtCore.QRect(90, 200, 46, 21))
        self.temp_value.setObjectName(_fromUtf8("temp_value"))
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.stackedWidget.addWidget(self.page_6)
        self.info_frame = QtGui.QFrame(self.centralwidget)
        self.info_frame.setGeometry(QtCore.QRect(10, 10, 161, 511))
        self.info_frame.setStyleSheet(_fromUtf8(""))
        self.info_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.info_frame.setObjectName(_fromUtf8("info_frame"))
        self.label_52 = QtGui.QLabel(self.info_frame)
        self.label_52.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.textBrowser = QtGui.QTextBrowser(self.info_frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 121, 192))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.main_but.setText(_translate("MainWindow", "Main", None))
        self.config_but.setText(_translate("MainWindow", "Configuration", None))
        self.pin_but.setText(_translate("MainWindow", "Pin", None))
        self.protec_but.setText(_translate("MainWindow", "Protection", None))
        self.monitor_but.setText(_translate("MainWindow", "Monitoring", None))
        self.voltage_box.setTitle(_translate("MainWindow", "Voltage", None))
        self.vin_label_main.setText(_translate("MainWindow", "VIN", None))
        self.vout_label_main.setText(_translate("MainWindow", "VOUT", None))
        self.label_3.setText(_translate("MainWindow", "V", None))
        self.label_4.setText(_translate("MainWindow", "V", None))
        self.procent_label1.setText(_translate("MainWindow", "%", None))
        self.procent_label2.setText(_translate("MainWindow", "%", None))
        self.nominal_label.setText(_translate("MainWindow", "Nominal", None))
        self.margin_high_label.setText(_translate("MainWindow", "Margin High", None))
        self.margin_low_label.setText(_translate("MainWindow", "Margin Low", None))
        self.configuration_box.setTitle(_translate("MainWindow", "Sequencing", None))
        self.dev_rise.setText(_translate("MainWindow", "Device Rise:", None))
        self.dev_fall.setText(_translate("MainWindow", "Device Fall:", None))
        self.delay.setText(_translate("MainWindow", "Delay", None))
        self.ton_delay_label.setText(_translate("MainWindow", "TON_DELAY:", None))
        self.toff_delay_label.setText(_translate("MainWindow", "TOFF_DELAY:", None))
        self.ton_rise_label.setText(_translate("MainWindow", "TON_RISE:", None))
        self.toff_fall_label.setText(_translate("MainWindow", "TOFF_FALL:", None))
        self.ton_max_label.setText(_translate("MainWindow", "TON_MAX:", None))
        self.toff_max_label.setText(_translate("MainWindow", "TOFF_MAX:", None))
        self.label_39.setText(_translate("MainWindow", "ms", None))
        self.label_40.setText(_translate("MainWindow", "ms", None))
        self.label_41.setText(_translate("MainWindow", "ms", None))
        self.label_42.setText(_translate("MainWindow", "ms", None))
        self.label_43.setText(_translate("MainWindow", "ms", None))
        self.label_44.setText(_translate("MainWindow", "ms", None))
        self.vout_on_label.setText(_translate("MainWindow", "ON:", None))
        self.vout_ff_label.setText(_translate("MainWindow", "OFF:", None))
        self.label_47.setText(_translate("MainWindow", "V", None))
        self.label_48.setText(_translate("MainWindow", "V", None))
        self.ramping.setText(_translate("MainWindow", "Ramping", None))
        self.max_timing.setText(_translate("MainWindow", "Max Timing", None))
        self.vout.setText(_translate("MainWindow", "VOUT", None))
        self.protection_box.setTitle(_translate("MainWindow", "PMBus Protection Parameters", None))
        self.vout_ov_label.setText(_translate("MainWindow", "VOUT OV", None))
        self.vin_ov_label.setText(_translate("MainWindow", "VIN OV", None))
        self.warning_label.setText(_translate("MainWindow", "Warning Limit", None))
        self.iout_oc_label.setText(_translate("MainWindow", "IOUT", None))
        self.enable_label.setText(_translate("MainWindow", "Enable", None))
        self.temp_ot_label.setText(_translate("MainWindow", "TEMP", None))
        self.fault_label.setText(_translate("MainWindow", "Fault Limit", None))
        self.delay_label.setText(_translate("MainWindow", "Time Delay", None))
        self.v_label1.setText(_translate("MainWindow", "V", None))
        self.v_label2.setText(_translate("MainWindow", "V", None))
        self.v_label3.setText(_translate("MainWindow", "V", None))
        self.v_label4.setText(_translate("MainWindow", "V", None))
        self.v_label5.setText(_translate("MainWindow", "V", None))
        self.v_label6.setText(_translate("MainWindow", "V", None))
        self.v_label7.setText(_translate("MainWindow", "V", None))
        self.v_label8.setText(_translate("MainWindow", "V", None))
        self.ms_label1.setText(_translate("MainWindow", "ms", None))
        self.ms_label2.setText(_translate("MainWindow", "ms", None))
        self.ms_label3.setText(_translate("MainWindow", "ms", None))
        self.ms_label4.setText(_translate("MainWindow", "ms", None))
        self.alert_label.setText(_translate("MainWindow", "Alert", None))
        self.vout_uv_label.setText(_translate("MainWindow", "VOUT UV", None))
        self.vin_uv_label.setText(_translate("MainWindow", "VIN UV", None))
        self.c_label1.setText(_translate("MainWindow", "°C", None))
        self.a_label1.setText(_translate("MainWindow", "A", None))
        self.ms_label5.setText(_translate("MainWindow", "ms", None))
        self.ms_label6.setText(_translate("MainWindow", "ms", None))
        self.c_label2.setText(_translate("MainWindow", "°C", None))
        self.a_label2.setText(_translate("MainWindow", "A", None))
        self.w_label.setText(_translate("MainWindow", "W", None))
        self.f_label.setText(_translate("MainWindow", "F", None))
        self.monitoring_box.setTitle(_translate("MainWindow", "PMBus Status Information", None))
        self.clear_faults_but.setText(_translate("MainWindow", "Clear Faults", None))
        self.vin_label.setText(_translate("MainWindow", "VIN:", None))
        self.vout_label.setText(_translate("MainWindow", "VOUT:", None))
        self.iout_label.setText(_translate("MainWindow", "IOUT:", None))
        self.temp_label.setText(_translate("MainWindow", "TEMP:", None))
        self.vin_value.setText(_translate("MainWindow", "0 V", None))
        self.vout_value.setText(_translate("MainWindow", "0 V", None))
        self.iout_value.setText(_translate("MainWindow", "0 A", None))
        self.temp_value.setText(_translate("MainWindow", "0 °C", None))
        self.label_52.setText(_translate("MainWindow", "Device info:", None))

    def page1(self):
        self.stackedWidget.setCurrentIndex(0)

    def page2(self):
        self.stackedWidget.setCurrentIndex(1)

    def page3(self):
        self.stackedWidget.setCurrentIndex(2)

    def page4(self):
        self.stackedWidget.setCurrentIndex(3)

    def page5(self):
        self.stackedWidget.setCurrentIndex(4)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

