#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
from PyQt4 import QtGui, QtCore


class Graph(QtGui.QWidget):
    def __init__(self):
        super(Graph, self).__init__()
        self.pixmap = QtGui.QPixmap(631, 351)
        self.pixmap.fill(QtCore.Qt.transparent)

    def generate_graph(self):
        paint = QtGui.QPainter(self.pixmap)
        self.draw_lines(paint)

    def paintEvent(self, e):
        qp = QtGui.QPainter(self)
        #self.draw_lines(qp)
        self.generate_graph()
        qp.drawPixmap(0, 0, self.pixmap)  # load graph from Bitmap

    def draw_lines(self, qp):
        pen = QtGui.QPen(QtCore.Qt.black, 2, QtCore.Qt.SolidLine)
        qp.setPen(pen)
        qp.drawLine(60, 20, 60, 190)  # y axis
        self.draw_arrow_head(qp, 55, 20, 65, 20, 60, 15)
        qp.drawLine(60, 190, 600, 190)  # x axis
        self.draw_arrow_head(qp, 600, 185, 600, 195, 605, 190)

        pen = QtGui.QPen(QtCore.Qt.darkGray, 1, QtCore.Qt.SolidLine)  # horizontal dashed
        pen.setStyle(QtCore.Qt.DashLine)
        qp.setPen(pen)
        qp.drawLine(60, 40, 600, 40)
        qp.drawLine(60, 160, 600, 160)

        pen = QtGui.QPen(QtCore.Qt.darkGray, 1, QtCore.Qt.SolidLine)  # vertical dashed
        pen.setStyle(QtCore.Qt.DashLine)
        qp.setPen(pen)
        qp.drawLine(130, 40, 130, 190)
        qp.drawLine(200, 40, 200, 190)
        qp.drawLine(270, 40, 270, 190)
        qp.drawLine(340, 40, 340, 190)
        qp.drawLine(410, 40, 410, 190)
        qp.drawLine(480, 40, 480, 190)
        qp.drawLine(550, 40, 550, 190)

        pen = QtGui.QPen(QtCore.Qt.blue, 2, QtCore.Qt.SolidLine)  # draw graph
        qp.setPen(pen)
        qp.drawLine(60, 189, 130, 189)
        qp.drawLine(130, 189, 200, 40)

        qp.drawLine(410, 40, 480, 189)  # when cut off is 0
        qp.drawLine(480, 189, 550, 189)  # when cut off is 0

        pen.setStyle(QtCore.Qt.CustomDashLine)
        pen.setDashPattern([35, 13, 10, 13])
        qp.setPen(pen)
        qp.drawLine(200, 40, 410, 40)

        pen = QtGui.QPen(QtCore.Qt.black, 1, QtCore.Qt.SolidLine)  # draw bottom legend lines
        qp.setPen(pen)
        qp.drawLine(60, 195, 60, 225)
        qp.drawLine(130, 195, 130, 225)
        qp.drawLine(200, 195, 200, 215)
        qp.drawLine(270, 195, 270, 225)
        qp.drawLine(340, 195, 340, 225)
        qp.drawLine(410, 195, 410, 225)
        qp.drawLine(480, 195, 480, 215)
        qp.drawLine(550, 195, 550, 225)

        # draw arrows
        qp.drawLine(70, 200, 120, 200)
        self.draw_arrow_head(qp, 70, 195, 70, 205, 65, 200)
        self.draw_arrow_head(qp, 120, 195, 120, 205, 125, 200)
        qp.drawLine(140, 200, 190, 200)
        self.draw_arrow_head(qp, 140, 195, 140, 205, 135, 200)
        self.draw_arrow_head(qp, 190, 195, 190, 205, 195, 200)
        qp.drawLine(140, 220, 260, 220)
        self.draw_arrow_head(qp, 140, 215, 140, 225, 135, 220)
        self.draw_arrow_head(qp, 260, 215, 260, 225, 265, 220)
        qp.drawLine(350, 200, 400, 200)
        self.draw_arrow_head(qp, 350, 195, 350, 205, 345, 200)
        self.draw_arrow_head(qp, 400, 195, 400, 205, 405, 200)
        qp.drawLine(420, 200, 470, 200)
        self.draw_arrow_head(qp, 420, 195, 420, 205, 415, 200)
        self.draw_arrow_head(qp, 470, 195, 470, 205, 475, 200)
        qp.drawLine(420, 220, 540, 220)
        self.draw_arrow_head(qp, 420, 215, 420, 225, 415, 220)
        self.draw_arrow_head(qp, 540, 215, 540, 225, 545, 220)

    def draw_arrow_head(self, qp, a, b, c, d, e, f):
        # draw arrow head
        qp.setBrush(QtGui.QBrush(QtCore.Qt.black))
        points = [QtCore.QPoint(a, b), QtCore.QPoint(c, d), QtCore.QPoint(e, f)]
        needle = QtGui.QPolygon(points)
        qp.drawPolygon(needle)

